// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package issuedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actor struct {
	ID             int64
	Kind           string
	UserID         pgtype.Int8
	AgentRoleKey   pgtype.Text
	AgentSessionID pgtype.Int8
	WorkflowRunID  pgtype.Int8
	DisplayName    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AgentSession struct {
	ID                      int64
	RunnerID                pgtype.Int8
	RepoID                  pgtype.Int8
	IssueNumber             pgtype.Int4
	Status                  string
	Role                    string
	Model                   string
	AgentImage              string
	WorkingBranch           string
	BaseBranch              string
	HostAddendum            string
	Env                     []byte
	SessionTokenPrefix      string
	SessionTokenHash        string
	SessionTokenSealed      pgtype.Text
	SessionTokenRevokedAt   pgtype.Timestamptz
	ExitCode                pgtype.Int4
	ErrorMessage            string
	CreatedAt               pgtype.Timestamptz
	ClaimedAt               pgtype.Timestamptz
	StartedAt               pgtype.Timestamptz
	EndedAt                 pgtype.Timestamptz
	RepoSha                 string
	RoleKey                 string
	CauseKind               string
	CauseID                 string
	RoleConfig              []byte
	ContainerID             string
	ContainerLastUsedAt     pgtype.Timestamptz
	ContainerCleanupPending bool
	ContainerStopPending    bool
	ContainerStoppedAt      pgtype.Timestamptz
	RunningJobs             int32
	CreatedByActorID        int64
	ActorID                 pgtype.Int8
}

type AgentSessionInput struct {
	ID         int64
	SessionID  int64
	Seq        int32
	Payload    []byte
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type AgentSessionMessage struct {
	ID         int64
	SessionID  int64
	Seq        int32
	Kind       string
	Role       string
	Content    string
	EventName  string
	ToolCallID string
	ToolName   string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

type BranchProtection struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Contribution struct {
	ID              int64
	RepoID          int64
	IssueID         int64
	SessionID       int64
	AgentRole       string
	RefName         string
	HeadSha         string
	BaseSha         string
	Title           string
	Description     string
	Status          string
	Mergeable       bool
	MergeMode       string
	ChangedPaths    []string
	Files           int32
	Additions       int32
	Deletions       int32
	MergedCommitSha string
	MergedAt        pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ActorID         int64
}

type Issue struct {
	ID             int64
	RepoID         int64
	Number         int64
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ParentID       pgtype.Int8
	ParentNumber   int64
	ActorID        int64
}

type IssueAttachment struct {
	ID               int64
	RepoID           int64
	IssueID          int64
	CommentID        pgtype.Int8
	StorageKey       string
	OriginalName     string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Status           string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	DisplayName      string
	Inline           bool
	ActorID          int64
}

type IssueComment struct {
	ID            int64
	IssueID       int64
	Body          string
	FilePath      string
	Line          int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ActorID       int64
	SourceIssueID pgtype.Int4
}

type IssueCounter struct {
	RepoID int64
	Next   int64
}

type IssueDependency struct {
	ID          int64
	RepoID      int64
	IssueID     int64
	DependsOnID int64
	CreatedBy   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
}

type IssueEvent struct {
	ID        int64
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   int64
	CreatedAt pgtype.Timestamptz
}

type Organization struct {
	ID          int64
	Name        string
	DisplayName string
	Description string
	AvatarUrl   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	ActorID     int64
}

type OrganizationMember struct {
	OrgID   int64
	UserID  int64
	Role    string
	AddedAt pgtype.Timestamptz
	ActorID int64
}

type Questionnaire struct {
	ID             int64
	IssueID        int64
	Title          string
	Description    string
	Status         string
	CreatedByAgent string
	CreatedAt      pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
	ClosedReason   string
}

type QuestionnaireAnswer struct {
	ID              int64
	QuestionnaireID int64
	Answers         []byte
	SubmittedAt     pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ActorID         int64
}

type QuestionnaireQuestion struct {
	ID              int64
	QuestionnaireID int64
	Position        int32
	QuestionText    string
	Qtype           string
	Options         []byte
	Required        bool
}

type Repo struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
}

type RepoMember struct {
	RepoID  int64
	UserID  int64
	Role    string
	AddedAt pgtype.Timestamptz
	ActorID int64
}

type RepoVariable struct {
	ID        int64
	RepoID    int64
	Name      string
	Value     string
	Kind      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Runner struct {
	ID                  int64
	Name                string
	OwnerUserID         pgtype.Int8
	Visibility          string
	Status              string
	Capabilities        []byte
	LastHeartbeatAt     pgtype.Timestamptz
	EnrollTokenPrefix   string
	EnrollTokenHash     string
	EnrollTokenUsedAt   pgtype.Timestamptz
	AgentTokenPrefix    pgtype.Text
	AgentTokenHash      pgtype.Text
	AgentTokenRevokedAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ActorID             int64
}

type Todo struct {
	ID        int64
	IssueID   int64
	Content   string
	Status    string
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WorkflowJobLog struct {
	ID               int64
	WorkflowJobRunID int64
	Stream           string
	Line             string
	CreatedAt        pgtype.Timestamptz
	StepID           pgtype.Text
}

type WorkflowJobPhase struct {
	ID               int64
	WorkflowJobRunID int64
	Phase            string
	Status           string
	SequenceIndex    int32
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	ExitCode         pgtype.Int4
	ErrorMessage     string
	ImageRef         string
	CreatedAt        pgtype.Timestamptz
}

type WorkflowJobRun struct {
	ID                int64
	WorkflowRunID     int64
	JobKey            string
	DisplayName       string
	Status            string
	SequenceIndex     int32
	WorkingDirectory  string
	TimeoutMinutes    int32
	RunnerID          pgtype.Int8
	ContainerID       pgtype.Text
	EnvJson           []byte
	StepsJson         []byte
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	ExitCode          pgtype.Int4
	ErrorMessage      string
	CreatedAt         pgtype.Timestamptz
	StepOutputsJson   []byte
	JobOutputsJson    []byte
	JobOutputsRawJson []byte
}

type WorkflowRun struct {
	ID                        int64
	RepoID                    int64
	WorkflowName              string
	SourceFile                string
	Status                    string
	EventName                 string
	CauseID                   pgtype.Int8
	Ref                       string
	CommitSha                 string
	ContainerSnapshotJson     []byte
	TriggerPayloadJson        []byte
	StartedAt                 pgtype.Timestamptz
	FinishedAt                pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	WorkflowToken             string
	TriggerActorKind          string
	TriggerActorUserID        pgtype.Int8
	TriggerActorRoleKey       string
	TriggerActorWorkflowRunID pgtype.Int8
	TriggerActorDisplayName   string
	RunActorKind              string
	RunActorUserID            pgtype.Int8
	RunActorRoleKey           string
	RunActorWorkflowRunID     pgtype.Int8
	RunActorDisplayName       string
}
